const GlobalVariables = {
  variables: {
    clientId:
      '515714145009-7vnddn3a5q3l2vp4np78koohjjb7phie.apps.googleusercontent.com',
  },
  color: {
    background: 'rgb(18, 18, 18)',
    navBar: 'rgba(18, 18, 18, .80)',
    mainCard: 'rgb(35, 35, 35)',
    secondaryLayer: 'rgb(50, 50, 50)',
    pressed: 'rgb(91, 91, 91)',
    title: '#ffffff',
    secondaryText: 'rgb(163, 163, 163)',
    bringFocus: 'rgb(192, 147, 255)',
    clickable: '#03dac5',
    positive: '#62c122',
    negative: '#ffde03',
    longPress: 'rgb(109, 108, 108)',
  },
  styles: {
    mainCard: {
      backgroundColor: 'rgb(35, 35, 35)',
      margin: 12,
      borderWidth: 1,
      borderStyle: 'solid',
      borderRadius: 15,
      borderColor: 'rgb(91, 91, 91)',
      paddingTop: 8,
      justifyContent: 'flex-end',
      overflow: 'hidden',
      position: 'relative',
    },
    addBtn: {
      backgroundColor: '#03dac5',
      height: 60,
      width: 60,
      right: 0,
      bottom: 0,
      position: 'absolute',
      borderRadius: 50,
      padding: 10,
      justifyContent: 'center',
      margin: 15,
    },
    commentBase: {
      display: 'flex',
      maxWidth: 250,
      backgroundColor: 'rgb(50, 50, 50)',
      marginVertical: 4,
      marginHorizontal: 4,
      borderStyle: 'solid',
      borderWidth: 1,
      borderRadius: 20,
      borderColor: 'rgb(50, 50, 50)',
      paddingHorizontal: 8,
      paddingBottom: 6,
    },
    bubbleTag: {
      right: 0,
      borderStyle: 'solid',
      borderColor: 'white',
      backgroundColor: 'rgb(192, 147, 255)',
      borderRadius: 12,
      marginTop: 5,
      marginBottom: 5,
      marginLeft: 7,
      marginRight: 15,
      paddingLeft: 6,
      paddingRight: 6,
      height: 20,
    },
    secondaryText: {
      fontSize: 14,
      color: 'rgb(163, 163, 163)',
    },
    title: {
      fontSize: 16,
      color: 'white',
    },
    titleInput: {
      backgroundColor: 'rgb(35, 35, 35)',
      color: 'rgb(163, 163, 163)',
      marginVertical: 5,
    },
    cardText: {
      marginTop: 5,
      marginBottom: 5,
      marginLeft: 15,
      marginRight: 7,
      maxWidth: 250,
    },
    listItem: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      margin: 2,
      borderStyle: 'dotted',
      borderWidth: 1,
    },
    divider: {
      borderBottomColor: 'rgb(163, 163, 163)',
      borderBottomWidth: 1,
      marginHorizontal: 5,
      marginVertical: 9,
    },
    viewportRoot: {
      flex: 1,
      backgroundColor: 'rgb(18, 18, 18)',
    },
    loadingText: {
      fontSize: 16,
      color: '#ffffff',
      margin: 5,
    },
    spinner: {
      alignItems: 'center',
    },
  },
};

export default GlobalVariables;
